pipeline{
    agent { node {label 'agent-1'} }
    stages{
        stage('Init'){
            steps{
                sh '''
                ls -ltr
                pwd
                cd /home/centos/workspace/terraform-jenkins-pipeline/01-vpc
                terraform init 
                '''
            }
        }
        stage('Plan')
        {
            steps{
                sh '''
                 ls -ltr
                 pwd
                 cd /home/centos/workspace/terraform-jenkins-pipeline/01-vpc
                 terraform plan -lock=false
                '''
            }
        }
        stage('Approval')
        {
            steps{
                input "Shall I approve?"
            }
        }
        stage('Apply')
        {
            steps{
                sh '''
                  ls -ltr
                  pwd
                  cd /home/centos/workspace/terraform-jenkins-pipeline/01-vpc
                  terraform apply -auto-approve
                '''
            }
        }
    }
}