pipeline{
    agent { node {label 'agent-1'} }
    stages{
        stage('Init'){
            steps{
                sh '''
                ls -ltr
                pwd
                terrraform init 
                '''
            }
        }
    }
}